name: Push To Kyso
on:
  push:
    branches:
      - main
jobs:
  Push-To-Kyso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo ${{secrets.KYSO_TOKEN}}
      - run: npm install -g kyso
      - run: kyso login --kysoInstallUrl https://insitro.kyso.io --provider kyso --username kyle@kyso.io --token ${{secrets.CUSTOMER_TEST}}
      - run: kyso push
